language: python

os: linux
dist: xenial

install: pip install -r requirements.txt
jobs:
  include:
  - stage: test
    script: python -m pytest -v tests/test_dice.py
  - stage: build
    script: skip
    before_deploy:
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
    deploy:
      provider: heroku
      api_key: $HEROKU_AUTH_TOKEN
      app: test-ci-d
      on:
        branch: dev
  - stage: production
    script: skip
    before_deploy:
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
    deploy:
      provider: heroku
      api_key: $HEROKU_AUTH_TOKEN
      app: test-ci-p
      on:
        branch: main