language: python
os: linux
dist: xenial
install: pip install -r requirements.txt
jobs:
  include:
  - stage: test
    script: python -m pytest -v tests/test_dice.py
  - stage: build
    script: skip
    before_deploy:
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
    deploy:
      provider: heroku
      api_key: D07nklOrXy0gOS4ELEJNq24w+i6vH4zsf/MvHWfzMB13gOqpU6Q/irkhJdK5Gsai6MWqDQQ3XZlsCy4O1NvxGFNqvKSXF6RedfxzTMOfZq8rW+w1qQCSXHT4PCzU0IEZrZ/baZm6VSa1iygEXC9YU1/EcuPbYTe36CCU45jzzxFvSAeAkAtqo3BTS7GLkVI6QxtF14Eqb8ArqGtspo4zPgJUavC3Qc1GjYBMFC5wgKu3r2jVuOCVW7bPvJyP8cPunjvOBpaviWLDnCgUa3WtwvW37waLhsHLSvrsEkFpSf0TmrENHOrgnMU3MuPARgQrEnjM9d8DEEzicLOruP1W21HcknvsFLw0Hkji8q4/NizNjrACeAcdWDG7U0a/aHfAUr8+P9+Z4w6QxmlnOldmjaYrpK1iGqoa2PJMcOhvJeyi7z0R9QBUtzt16jAji6oEsvzjDO7oSvIaNOfv3VJa9jOAx4C2KY73SZLHecoU6giDKQ6yPse1bWqBSVxw3E07VAj+jwYWB1JiIRkypDvdrhV+cN4c7KaBREeNEVtoN4/WlnVDmgNj0c1jXmzJRw82ddP6rSPrvWxH2tJqcqMosMxSbO6dAUbaTMFCWDxD0ViArqGcdf1AXwDFAaY73OvNdsWVR2ENzM3AMg0nzS6S2I9xgPsHRBcPFCWeAOI2n2Q=
      app: test-ci-d
      on:
        branch: dev
  - stage: production
    script: skip
    deploy:
      provider: heroku
      api_key: D07nklOrXy0gOS4ELEJNq24w+i6vH4zsf/MvHWfzMB13gOqpU6Q/irkhJdK5Gsai6MWqDQQ3XZlsCy4O1NvxGFNqvKSXF6RedfxzTMOfZq8rW+w1qQCSXHT4PCzU0IEZrZ/baZm6VSa1iygEXC9YU1/EcuPbYTe36CCU45jzzxFvSAeAkAtqo3BTS7GLkVI6QxtF14Eqb8ArqGtspo4zPgJUavC3Qc1GjYBMFC5wgKu3r2jVuOCVW7bPvJyP8cPunjvOBpaviWLDnCgUa3WtwvW37waLhsHLSvrsEkFpSf0TmrENHOrgnMU3MuPARgQrEnjM9d8DEEzicLOruP1W21HcknvsFLw0Hkji8q4/NizNjrACeAcdWDG7U0a/aHfAUr8+P9+Z4w6QxmlnOldmjaYrpK1iGqoa2PJMcOhvJeyi7z0R9QBUtzt16jAji6oEsvzjDO7oSvIaNOfv3VJa9jOAx4C2KY73SZLHecoU6giDKQ6yPse1bWqBSVxw3E07VAj+jwYWB1JiIRkypDvdrhV+cN4c7KaBREeNEVtoN4/WlnVDmgNj0c1jXmzJRw82ddP6rSPrvWxH2tJqcqMosMxSbO6dAUbaTMFCWDxD0ViArqGcdf1AXwDFAaY73OvNdsWVR2ENzM3AMg0nzS6S2I9xgPsHRBcPFCWeAOI2n2Q=
      app: test-ci-p
      on:
        branch: main
notifications:
  slack:
    secure: EfDm336D6PRtm2m17o8VagqU/ErplR4LyE7HlIbPQnxoqkj5RUUaHVe3r+aIqs7jcVLGGJ8H5ZFMpvSzF0ojig2XbhFJAjqrMuI61bPlJzyKHLpafPqmVqOvJ53qHqqmgjYSxCdxz2Nv0sNTPX5G6VUIYxxQZ1voDVf+AMzNiaMa913hA93sV5Ozbc+hviBB5Ldyf+chyAbAwq3l5ODHUPqkZ/5NFTLI6EDTN0ApSrHb8lTvvJkrKvQU700ixYqs9RHsjc0zQmGBqNyeX0Ace1pjkcrsw29l0hFhOzUeEU8bZG7UPQHLeoF01n8vYXFXsHOZV4YfZ2xDDytlQfSbIaY/JsQhm5kqBSO1mFBYVStCRuIj9v/CxgyZbsOoCRGfGFvFFDtnqeRjwv5pIxot3H55f6kzMTZ0kllg8mx2B0xWZyTbnWw31+I2zrEdNXbPQSvoeDn/asbZn1ZuxkYzBZqFBKLq+vclyWDmt3/PciLa4j8DQ2HD1eAcmT36c4dOuJ3QZTy+gNtzpsRPUMbsbFr/B1SKQm5/eAyOk7CbHLVYjHctdkBmn/GK+tHz2796mIIHtVCYYrzrHLc1NP18QfV7byUlw1B3d7uP9BPvju4+GdzCSbpbvyxpQ51OvMZ/FaDqpO7Pj1MSLXS3kcfvn5CsZoNkDEIWSl/44LPf5+g=
