language: python
os: linux
dist: xenial
install: pip install -r requirements.txt
jobs:
  include:
  - stage: test
    script: python -m pytest -v tests/test_dice.py
  - stage: build
    script: skip
    before_deploy:
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
    deploy:
      provider: heroku
      api_key: b1HjGFZTgaRDkY9JkeSXMMIUbPlZZ/TvcMRP7mQUFU3+8qswUZ2dxPnhQwfXWn7QEd1m8PU5Xysw8Il7fvZwsUVdLrbv0Q68/x8KkEvUkSB7c+z51AqSPUCf0D7s+wXmZCCsP5463e+ahPqlZWc5yeB/5akf1oaMNZVmVGdUX3koCV+DOQU+hdkgFFaMDZ1CFvYRWuiaEcdkM6jvqa86mw9+ppyTwWEK5kkmKvQXCefl+H7wd8+nVkrcIUuxtxl8Uq/l8wf6QtksvvbbN5t1LATXSwoXv7QSxwBB13Rhjr4LHhxAqdL19Oav7tTyznRn0DP1RciMaSxgK3CgLTvHzJlUwI3eEAcJlfdj4vHgLXnHxDm3P58lgaU53v2ZJRa0CjnppHv1bumk8S908PzoaOtpT1+eGqkU/hNt9NVOrs+NJgFYrfUp/IURU1GjlB3Pj8zBSMAmbKcC0KLrpMg7nCBLMm1oid2gBlyT/txNAMgPTTbT2hNaTftXYeP4eyLlcW+cCWAKBkGkGeziRL5swewtm2zZ51hZPpIafl2gXL+MN6aoxRZrb8+j+kqRMyCqL9dA0a2DagCpyy9DI3KkTskpqp+lPRmUVExwNI3pR+8On5zAX4RLks1iUANeaQ68CrluT3ThbW5rE6WHn2+EVAXtGUrvn15PUv+c8F8NH5g=
      app: test-ci-d
      on:
        branch: dev
  - stage: production
    script: skip
    deploy:
      provider: heroku
      api_key: b1HjGFZTgaRDkY9JkeSXMMIUbPlZZ/TvcMRP7mQUFU3+8qswUZ2dxPnhQwfXWn7QEd1m8PU5Xysw8Il7fvZwsUVdLrbv0Q68/x8KkEvUkSB7c+z51AqSPUCf0D7s+wXmZCCsP5463e+ahPqlZWc5yeB/5akf1oaMNZVmVGdUX3koCV+DOQU+hdkgFFaMDZ1CFvYRWuiaEcdkM6jvqa86mw9+ppyTwWEK5kkmKvQXCefl+H7wd8+nVkrcIUuxtxl8Uq/l8wf6QtksvvbbN5t1LATXSwoXv7QSxwBB13Rhjr4LHhxAqdL19Oav7tTyznRn0DP1RciMaSxgK3CgLTvHzJlUwI3eEAcJlfdj4vHgLXnHxDm3P58lgaU53v2ZJRa0CjnppHv1bumk8S908PzoaOtpT1+eGqkU/hNt9NVOrs+NJgFYrfUp/IURU1GjlB3Pj8zBSMAmbKcC0KLrpMg7nCBLMm1oid2gBlyT/txNAMgPTTbT2hNaTftXYeP4eyLlcW+cCWAKBkGkGeziRL5swewtm2zZ51hZPpIafl2gXL+MN6aoxRZrb8+j+kqRMyCqL9dA0a2DagCpyy9DI3KkTskpqp+lPRmUVExwNI3pR+8On5zAX4RLks1iUANeaQ68CrluT3ThbW5rE6WHn2+EVAXtGUrvn15PUv+c8F8NH5g=
      app: test-ci-p
      on:
        branch: main
notifications:
  slack:
    secure: EfDm336D6PRtm2m17o8VagqU/ErplR4LyE7HlIbPQnxoqkj5RUUaHVe3r+aIqs7jcVLGGJ8H5ZFMpvSzF0ojig2XbhFJAjqrMuI61bPlJzyKHLpafPqmVqOvJ53qHqqmgjYSxCdxz2Nv0sNTPX5G6VUIYxxQZ1voDVf+AMzNiaMa913hA93sV5Ozbc+hviBB5Ldyf+chyAbAwq3l5ODHUPqkZ/5NFTLI6EDTN0ApSrHb8lTvvJkrKvQU700ixYqs9RHsjc0zQmGBqNyeX0Ace1pjkcrsw29l0hFhOzUeEU8bZG7UPQHLeoF01n8vYXFXsHOZV4YfZ2xDDytlQfSbIaY/JsQhm5kqBSO1mFBYVStCRuIj9v/CxgyZbsOoCRGfGFvFFDtnqeRjwv5pIxot3H55f6kzMTZ0kllg8mx2B0xWZyTbnWw31+I2zrEdNXbPQSvoeDn/asbZn1ZuxkYzBZqFBKLq+vclyWDmt3/PciLa4j8DQ2HD1eAcmT36c4dOuJ3QZTy+gNtzpsRPUMbsbFr/B1SKQm5/eAyOk7CbHLVYjHctdkBmn/GK+tHz2796mIIHtVCYYrzrHLc1NP18QfV7byUlw1B3d7uP9BPvju4+GdzCSbpbvyxpQ51OvMZ/FaDqpO7Pj1MSLXS3kcfvn5CsZoNkDEIWSl/44LPf5+g=
